### PR TITLE
Improvements2

### PR DESCRIPTION
**Pull request by konykon**
I modified the commit descriptions in order to be more clear and I merged those commits that were forming part of the same change.
I didn't manage to push them on #11 Improvements PR so I created Improvements2!

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
Until we fix https://github.com/konykon/django-app/pull/9 we won't know if tests are passing here. Did they in your machine?

**Comment by konykon** [comment]
Tests are passing locally but the main branch is now obsolete, so I would like to implement testing with factory boy to the updated code which will include the new urls.

**Comment by sauloperez** [comment]
By the CI's output you can see that the test factories are missing. You should be able to fix it by rebasing onto master.

**Comment by sauloperez** [comment]
Tests are passing :tada:

**Review by sauloperez — APPROVED** [review]

**Pull request merged**
